AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lexbot-rag-lambda

  Sample SAM Template for lexbot-rag-lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  LexBotRagFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: lexbot_rag.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  
  LexBotRagFunction:
    Description: "LexBot Rag Lambda Function ARN"
    Value: !GetAtt LexBotRagFunction.Arn
  LexBotRagFunctionIamRole:
    Description: "Implicit IAM Role created for LexBot Rag function"
    Value: !GetAtt LexBotRagFunctionRole.Arn

